// src/plugins/vuetify.js
import "@mdi/font/css/materialdesignicons.css"; // Ensure you are using css-loader
import Vue from "vue";
import Vuetify, {
  VApp,
  VNavigationDrawer,
  VContent,
  VContainer,
  VRow,
  VCol,
  VForm,
  VTextField,
  VTextarea,
  VSelect,
  VAutocomplete,
  VCheckbox,
  VBtn,
  VIcon,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelHeader,
  VExpansionPanelContent,
  VCard,
  VCardTitle,
  VCardSubtitle,
  VCardText,
  VCardActions,
  VPagination,
  VList,
  VListItemGroup,
  VListItem,
  VListItemTitle,
  VListItemSubtitle,
  VListItemContent,
  VListItemAvatar,
  VListItemIcon,
  VImg,
  VTabs,
  VTabsSlider,
  VTab,
  VTabItem,
  VMenu,
  VTooltip,
  VSpacer,
  VFadeTransition,
  VFabTransition,
  VAlert,
  VDialog
} from "vuetify/lib";
import * as directives from "vuetify/lib/directives";

Vue.use(Vuetify, {
  components: {
    VApp,
    VNavigationDrawer,
    VContent,
    VContainer,
    VRow,
    VCol,
    VForm,
    VTextField,
    VTextarea,
    VSelect,
    VAutocomplete,
    VCheckbox,
    VBtn,
    VIcon,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VCard,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VPagination,
    VList,
    VListItemGroup,
    VListItem,
    VListItemTitle,
    VListItemSubtitle,
    VListItemContent,
    VListItemAvatar,
    VListItemIcon,
    VImg,
    VTabs,
    VTabsSlider,
    VTab,
    VTabItem,
    VMenu,
    VTooltip,
    VSpacer,
    VFadeTransition,
    VFabTransition,
    VAlert,
    VDialog
  },
  icons: {
    iconfont: "mdi" // default - only for display purposes
  },
  directives
});

const opts = {};

export default new Vuetify(opts);
